In [5]:
#Example 1 - Hello world
print("Hello world")

Hello world


In [6]:
#Exercise 1 - Shoutout to Roadrunners
print("Hello Roadrunners! Good luck on your Fall 2022 semester!")

Hello Roadrunners! Good luck on your Fall 2022 semester!


In [7]:
# Example 2 - scalar varables and operators

a = 5          # create a variable named a that contains the value 5
b = 10         # create a variable named b that contains the value 10

# if you're not going to use the variables very often, you can do the math in the print statement.

print ("a+b equals ", a+b)  # output the sum of a+b
print ("a-b equals ", a-b)  # output the difference of a-b
print ("a*b equals ", a*b)  # output the results when a is multipled by b

# if you're going to use the variables later on, create variables with the results.

c = a*b       # do the math to put a*b into c
print (c)
# or alternately
print ('c = ',c)

d = a**b      # do the math of raising a to the b power
print (d)

a+b equals  15
a-b equals  -5
a*b equals  50
50
c =  50
9765625


In [9]:
#Exercise 2: Create a variable with the name of f, and put the value of 20 in it.
# Create another variable called g 15 in it. Add f and g and output the results.
# Multiply g and a and output the results.
f = 20
g = 15

print("f + g =", f+g)
print("g * a =", g*a)

f + g = 35
g * a = 75


In [10]:
# Example 3 - lists and operators

A = [1, 2, 3, 4]       # create a list of these in A
B = [5, 6, 7, 8]       # create a list of these in B

print("A+B is ",A+B)

A+B is  [1, 2, 3, 4, 5, 6, 7, 8]


In [11]:
# Example 4 - numpy, vectors and operators
import numpy as np              # importing the library numpy and shortening the name to np

C = np.array([3,6,9,12,15,18])  # creating a vector of 6 integer values (dim 1x6)
print(C)                        # outputing the vector C

print(C[0])                     # output the first value in C (remember, the index starts at 0)
print(C[3])                     # output the fourth value in C
print(C[5])                     # output the sixth value in C
print(C[1])                     # output the second value in C

totalC = C[0]+C[1]+C[2]+C[3]+C[4]+C[5]  # calculate the sum of C
print ('Sum of C is ', totalC)

C5_C0 = C[5]-C[0]               # calculate the difference between the last and first value in C
print ('The diff between the first and last values in C is ',C5_C0)

[ 3  6  9 12 15 18]
3
12
18
6
Sum of C is  63
The diff between the first and last values in C is  15


In [13]:
#Exercise 3: Create a variable named c with 4 values in it, containing the values 10, 20, 30 and 40, in that order.
#Output the entire variable. Add the first and last values and output them.
c = np.array([10, 20, 30, 40])
print(c)

c3_c0 = c[0] + c[3]
print("The sum of the first and last value equals", c3_c0)

[10 20 30 40]
The sum of the first and last value equals 50


In [14]:
## Example 5 - matrix and operators

D = np.array([(1,2,3), (4,5,6)])  # Create a 2x3 array (2 rows and 3 columns)
print(D)                          # output the array

print(D[0,0])                     # extract and output the first row, first column value
print(D[1,2])                     # extract and output the second row, third column value
print(D[:,2])                     # extract and output all rows and the third column
print(D[1,:])                     # extract and output the first row and all columns

Dtimes2 = D*2                     # multiple the array D piecewise times 2
Dtimes2

[[1 2 3]
 [4 5 6]]
1
6
[3 6]
[4 5 6]


array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [30]:
#Exercise 4: Create a variable named d that is a 3x2 array and has these values:
#    2    4
#
#    6    8

#   10   12
#
#Extract and output the 2nd row.  Add 3 to each value and output.

d = np.array([(-1,1), (3,5), (7,9)])
print(d[1])

dplus3 = d + 3
dplus3

[3 5]


array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

Question 1: My name is Melanie Schwartz. I am especially excited for this class because recently I completed a 22 week Full Stack Web Development
bootcamp. With that being said, programming is on my mind and I am glad to be adding another language to my tool box. Data Science intrigues me
because I consider myself to seek "fact over feeling", which data analysis supports. My academic journey has had its ups and downs, as I was previously
a Computer Science major and frankly, I struggled. This led me to take a semester off to pursue the web development boot camp to get a more hands on
understanding of computer programming. I am back this semester as a Multidisciplinary Studies major and am expected to graduate in Spring 2023.

Question 2: After setting up my IDE and a few tutorials on working with Jupyter, this lesson took me about an hour. The examples were very
straight forward and because of previous programming experience I was able to grasp these concepts (the matrices were the trickiest part).