In [32]:
# Setup
import numpy as np
import pandas as pd
x = [1,2,3]
y = [4,5,6]
z = [7,8,9]
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
# Example 1
np.concatenate([x,y,z],axis=0)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
# Example 2
x = [[1,2],[3,4]]
np.concatenate([x,x],axis=1)

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [35]:
# Example 3
z.append(y)
print(z)

[7, 8, 9, [4, 5, 6]]


In [36]:
# Example 4
surveys_df = pd.read_csv("surveys.csv")
surveys_df.info()
display(surveys_df.head(10))    # view the first 10 rows of data

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35549 entries, 0 to 35548
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   record_id        35549 non-null  int64  
 1   month            35549 non-null  int64  
 2   day              35549 non-null  int64  
 3   year             35549 non-null  int64  
 4   plot_id          35549 non-null  int64  
 5   species_id       34786 non-null  object 
 6   sex              33038 non-null  object 
 7   hindfoot_length  31438 non-null  float64
 8   weight           32283 non-null  float64
dtypes: float64(2), int64(5), object(2)
memory usage: 2.4+ MB


record_id  month  day  year  plot_id species_id sex  hindfoot_length  \
0          1      7   16  1977        2         NL   M             32.0   
1          2      7   16  1977        3         NL   M             33.0   
2          3      7   16  1977        2         DM   F             37.0   
3          4      7   16  1977        7         DM   M             36.0   
4          5      7   16  1977        3         DM   M             35.0   
5          6      7   16  1977        1         PF   M             14.0   
6          7      7   16  1977        2         PE   F              NaN   
7          8      7   16  1977        1         DM   M             37.0   
8          9      7   16  1977        1         DM   F             34.0   
9         10      7   16  1977        6         PF   F             20.0   

   weight  
0     NaN  
1     NaN  
2     NaN  
3     NaN  
4     NaN  
5     NaN  
6     NaN  
7     NaN  
8     NaN  
9     NaN

In [37]:
# Example 5
surveys_df.dtypes

record_id            int64
month                int64
day                  int64
year                 int64
plot_id              int64
species_id          object
sex                 object
hindfoot_length    float64
weight             float64
dtype: object

In [38]:
# Example 6
# Read in the first ten lines of the surveys table
survey_sub = surveys_df.head(10)
# Now the bottom 10 lines
survey_sub_last10 = surveys_df.tail(10)
# Reset the index values to the second dataframe so that it appends correctly
survey_sub_last10 = survey_sub_last10.reset_index(drop=True)
# drop=True option avoids adding a new index column with old index values

In [39]:
# Example 7
# Stack the DataFrames on top of each other
vertical_stack = pd.concat([survey_sub, survey_sub_last10], axis = 0)
# Stack the DataFrames side by side
horizontal_stack = pd.concat([survey_sub, survey_sub_last10], axis=1)

In [40]:
# Example 8
vertical_stack

record_id  month  day  year  plot_id species_id  sex  hindfoot_length  \
0          1      7   16  1977        2         NL    M             32.0   
1          2      7   16  1977        3         NL    M             33.0   
2          3      7   16  1977        2         DM    F             37.0   
3          4      7   16  1977        7         DM    M             36.0   
4          5      7   16  1977        3         DM    M             35.0   
5          6      7   16  1977        1         PF    M             14.0   
6          7      7   16  1977        2         PE    F              NaN   
7          8      7   16  1977        1         DM    M             37.0   
8          9      7   16  1977        1         DM    F             34.0   
9         10      7   16  1977        6         PF    F             20.0   
0      35540     12   31  2002       15         PB    F             26.0   
1      35541     12   31  2002       15         PB    F             24.0   
2      35542     12   31  2002       15         PB    F             26.0   
3      35543     12   31  2002       15         PB    F             27.0   
4      35544     12   31  2002       15         US  NaN              NaN   
5      35545     12   31  2002       15         AH  NaN              NaN   
6      35546     12   31  2002       15         AH  NaN              NaN   
7      35547     12   31  2002       10         RM    F             15.0   
8      35548     12   31  2002        7         DO    M             36.0   
9      35549     12   31  2002        5        NaN  NaN              NaN   

   weight  
0     NaN  
1     NaN  
2     NaN  
3     NaN  
4     NaN  
5     NaN  
6     NaN  
7     NaN  
8     NaN  
9     NaN  
0    23.0  
1    31.0  
2    29.0  
3    34.0  
4     NaN  
5     NaN  
6     NaN  
7    14.0  
8    51.0  
9     NaN

In [41]:
# Example 8
horizontal_stack

record_id  month  day  year  plot_id species_id sex  hindfoot_length  \
0          1      7   16  1977        2         NL   M             32.0   
1          2      7   16  1977        3         NL   M             33.0   
2          3      7   16  1977        2         DM   F             37.0   
3          4      7   16  1977        7         DM   M             36.0   
4          5      7   16  1977        3         DM   M             35.0   
5          6      7   16  1977        1         PF   M             14.0   
6          7      7   16  1977        2         PE   F              NaN   
7          8      7   16  1977        1         DM   M             37.0   
8          9      7   16  1977        1         DM   F             34.0   
9         10      7   16  1977        6         PF   F             20.0   

   weight  record_id  month  day  year  plot_id species_id  sex  \
0     NaN      35540     12   31  2002       15         PB    F   
1     NaN      35541     12   31  2002       15         PB    F   
2     NaN      35542     12   31  2002       15         PB    F   
3     NaN      35543     12   31  2002       15         PB    F   
4     NaN      35544     12   31  2002       15         US  NaN   
5     NaN      35545     12   31  2002       15         AH  NaN   
6     NaN      35546     12   31  2002       15         AH  NaN   
7     NaN      35547     12   31  2002       10         RM    F   
8     NaN      35548     12   31  2002        7         DO    M   
9     NaN      35549     12   31  2002        5        NaN  NaN   

   hindfoot_length  weight  
0             26.0    23.0  
1             24.0    31.0  
2             26.0    29.0  
3             27.0    34.0  
4              NaN     NaN  
5              NaN     NaN  
6              NaN     NaN  
7             15.0    14.0  
8             36.0    51.0  
9              NaN     NaN

In [42]:
# Example 9
vertical_stack = vertical_stack.reset_index(drop=True)
vertical_stack

record_id  month  day  year  plot_id species_id  sex  hindfoot_length  \
0           1      7   16  1977        2         NL    M             32.0   
1           2      7   16  1977        3         NL    M             33.0   
2           3      7   16  1977        2         DM    F             37.0   
3           4      7   16  1977        7         DM    M             36.0   
4           5      7   16  1977        3         DM    M             35.0   
5           6      7   16  1977        1         PF    M             14.0   
6           7      7   16  1977        2         PE    F              NaN   
7           8      7   16  1977        1         DM    M             37.0   
8           9      7   16  1977        1         DM    F             34.0   
9          10      7   16  1977        6         PF    F             20.0   
10      35540     12   31  2002       15         PB    F             26.0   
11      35541     12   31  2002       15         PB    F             24.0   
12      35542     12   31  2002       15         PB    F             26.0   
13      35543     12   31  2002       15         PB    F             27.0   
14      35544     12   31  2002       15         US  NaN              NaN   
15      35545     12   31  2002       15         AH  NaN              NaN   
16      35546     12   31  2002       15         AH  NaN              NaN   
17      35547     12   31  2002       10         RM    F             15.0   
18      35548     12   31  2002        7         DO    M             36.0   
19      35549     12   31  2002        5        NaN  NaN              NaN   

    weight  
0      NaN  
1      NaN  
2      NaN  
3      NaN  
4      NaN  
5      NaN  
6      NaN  
7      NaN  
8      NaN  
9      NaN  
10    23.0  
11    31.0  
12    29.0  
13    34.0  
14     NaN  
15     NaN  
16     NaN  
17    14.0  
18    51.0  
19     NaN

In [43]:
# Example 10
# write to csv
vertical_stack.to_csv('vertical_data.csv', index=False)

Exercise 1: There are two survey data files: surveys2001.csv and surveys2002.csv. Read the data into Python and combine the files to make a new variable. Create a plot of average plot weight by year, grouped by sex. Export your results as a CSV and make sure it reads back into Python properly.

In [53]:
surveys1 = pd.read_csv('surveys2001.csv')
surveys2 = pd.read_csv('surveys2002.csv')
dataMerge = pd.concat([surveys1, surveys2]).reset_index(drop=True)
print(dataMerge.to_string)
dataMerge.to_csv('MergedSurvey.csv',  index=False)

<bound method DataFrame.to_string of       Unnamed: 0  record_id  month  day  year  site_id species_id sex  \
0          31710      31711      1   21  2001        1         PB   F   
1          31711      31712      1   21  2001        1         DM   M   
2          31712      31713      1   21  2001        1         PB   M   
3          31713      31714      1   21  2001        1         DO   M   
4          31714      31715      1   21  2001        2         OT   M   
...          ...        ...    ...  ...   ...      ...        ...  ..   
3507       35540      35541     12   31  2002       15         PB   F   
3508       35541      35542     12   31  2002       15         PB   F   
3509       35542      35543     12   31  2002       15         PB   F   
3510       35546      35547     12   31  2002       10         RM   F   
3511       35547      35548     12   31  2002        7         DO   M   

      hindfoot_length  weight  
0                26.0    25.0  
1                37.0 

In [45]:
# Example 11
# Read in first 10 lines of surveys table
survey_sub = surveys_df.head(10)

# Import a small subset of the species data designed for this part of the lesson.
species_sub = pd.read_csv('speciesSubset.csv', keep_default_na=False, na_values=[""])

In [46]:
# Example 12
species_sub.columns

Index(['species_id', 'genus', 'species', 'taxa'], dtype='object')

In [47]:
# Example 13
survey_sub.columns

Index(['record_id', 'month', 'day', 'year', 'plot_id', 'species_id', 'sex',
       'hindfoot_length', 'weight'],
      dtype='object')

In [48]:
# Example 14
merged_inner = pd.merge(left=survey_sub, right=species_sub, left_on='species_id', right_on='species_id')
# In this case `species_id` is the only column name in  both dataframes, so if we skipped `left_on`
# And `right_on` arguments we would still get the same result

# What's the size of the output data?
merged_inner.shape
merged_inner

record_id  month  day  year  plot_id species_id sex  hindfoot_length  \
0          1      7   16  1977        2         NL   M             32.0   
1          2      7   16  1977        3         NL   M             33.0   
2          3      7   16  1977        2         DM   F             37.0   
3          4      7   16  1977        7         DM   M             36.0   
4          5      7   16  1977        3         DM   M             35.0   
5          8      7   16  1977        1         DM   M             37.0   
6          9      7   16  1977        1         DM   F             34.0   
7          7      7   16  1977        2         PE   F              NaN   

   weight       genus   species    taxa  
0     NaN     Neotoma  albigula  Rodent  
1     NaN     Neotoma  albigula  Rodent  
2     NaN   Dipodomys  merriami  Rodent  
3     NaN   Dipodomys  merriami  Rodent  
4     NaN   Dipodomys  merriami  Rodent  
5     NaN   Dipodomys  merriami  Rodent  
6     NaN   Dipodomys  merriami  Rodent  
7     NaN  Peromyscus  eremicus  Rodent

In [49]:
# Example 15
merged_left = pd.merge(left=survey_sub, right=species_sub, how='left', left_on='species_id', right_on='species_id')
merged_left

record_id  month  day  year  plot_id species_id sex  hindfoot_length  \
0          1      7   16  1977        2         NL   M             32.0   
1          2      7   16  1977        3         NL   M             33.0   
2          3      7   16  1977        2         DM   F             37.0   
3          4      7   16  1977        7         DM   M             36.0   
4          5      7   16  1977        3         DM   M             35.0   
5          6      7   16  1977        1         PF   M             14.0   
6          7      7   16  1977        2         PE   F              NaN   
7          8      7   16  1977        1         DM   M             37.0   
8          9      7   16  1977        1         DM   F             34.0   
9         10      7   16  1977        6         PF   F             20.0   

   weight       genus   species    taxa  
0     NaN     Neotoma  albigula  Rodent  
1     NaN     Neotoma  albigula  Rodent  
2     NaN   Dipodomys  merriami  Rodent  
3     NaN   Dipodomys  merriami  Rodent  
4     NaN   Dipodomys  merriami  Rodent  
5     NaN         NaN       NaN     NaN  
6     NaN  Peromyscus  eremicus  Rodent  
7     NaN   Dipodomys  merriami  Rodent  
8     NaN   Dipodomys  merriami  Rodent  
9     NaN         NaN       NaN     NaN

In [50]:
# Example 16
merged_left[ pd.isnull(merged_left.genus) ]

record_id  month  day  year  plot_id species_id sex  hindfoot_length  \
5          6      7   16  1977        1         PF   M             14.0   
9         10      7   16  1977        6         PF   F             20.0   

   weight genus species taxa  
5     NaN   NaN     NaN  NaN  
9     NaN   NaN     NaN  NaN

Exercise 2: The plots.csv file contains information about the type associated with each plot. Use that data to summarize the number of plots by plot type.
Calculate a diversity index of your choice for control vs rodent exclosure plots. The index should consider both species abundance and number of species. You might choose to use the simple biodiversity index described here which calculates diversity as:
the number of species in the plot / the total number of individuals in the plot = Biodiversity index.